### ISSUE TITLE
The model file is not being created in the models folder after training

### ISSUE THREAD

**Issue by bigman73** [samtecspg/rasa-api#1] opened 2017-06-15 17:01 UTC
I followed the instructions.
Rasa is running, I can parse for the basic greet
When I train using the /train api the response shows the process started
But no model file is created in the models folder
I did map the virtual folder in Docker settings

This is how the container logs look - the no model directory warning looks suspicious:
```
WARNING:root:backend 'mitie' specified in config, **but no model directory ('server_model_dir') is configured. Using 'hello-goodby' backend instead!**
INFO:root:using default hello-goodby backend
INFO:root:Started http server on port 5000
192.168.99.1 - - [2017-06-15 16:59:11] "GET / HTTP/1.1" 200 120 0.001127
```

**Training data:**
{
  "text": "show me chinese restaurants",
  "intent": "restaurant_search",
  "entities": [
    {
      "start": 8,
      "end": 15,
      "value": "chinese",
      "entity": "cuisine"
    }
  ]
}

**Comment by dcalvom** [comment] 2017-06-15 18:00
Hi @bigman73. If your training data is:

```
{
  "text": "show me chinese restaurants",
  "intent": "restaurant_search",
  "entities": [
    {
      "start": 8,
      "end": 15,
      "value": "chinese",
      "entity": "cuisine"
    }
  ]
}
```

You're not going to be able to train the model as this training data format is not the right format for rasa training. Please check [rasa training format](https://rasa-nlu.readthedocs.io/en/latest/dataformat.html) to get more information about it.

Another note is that your training file just contains one example. The minimum is 2, otherwise, training may fail.

I tried the training with this format, and I successfully trained the model and I have it on the model dir I mounted:

```
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "show me chinese restaurants",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 8,
            "end": 15,
            "value": "chinese",
            "entity": "cuisine"
          }
        ]
      },
	  {
        "text": "do you know chinese restaurants?",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 12,
            "end": 19,
            "value": "chinese",
            "entity": "cuisine"
          }
        ]
      }
    ]
  }
}
```

Regarding the `WARNING:root:backend 'mitie' specified in config, **but no model directory ('server_model_dir') is configured. Using 'hello-goodby' backend instead!**` message. It was shown because the first container is started without this parameter set. Once you have your model trained, you send this parameter as instructions explain in step 4.

**Comment by bigman73** [comment] 2017-06-15 18:10
Dude, you totally rock. Your docker is a life saver. 
If I could buy you an expensive beer, let me know :beer: 

It works. I can see the training take place (/status api works), and the files being created.

I do have a question about the rasa "workflow" - if I train using the API is there only way to get the model to work is the model files copy and restart? Can't the training become effective immediately, for example by using the model **name** parameter?

If not, I guess I can build an automatic process that has 2 docker containers - one for training and one for the actual parsing. And then the process will automatically copy the new model files and restart the parsing rasa docker per step 4 instructions.

**Comment by dcalvom** [comment] 2017-06-15 18:34
I'm glad it works.

Yeah, there is a way to do that. Since version 0.8.0 RASA allows to name models and load them in "hot mode".

Our latest image is not updated with those changes. But we have different [tags](https://hub.docker.com/r/samtecspg/rasa-api/tags/) for those versions of RASA. I recommend you to use `RASA_0.8.7_full` as it is our latest stable version being used. But as you can see we almost have all the tags for the latest RASA versions (Currently 0.8.11).

With the `RASA_0.8.7_full` tag, you are going to be able to name your models when using the train endpoint. 

For that, you use the `POST /train?model=yourModelName -d @trainingData.json`. Once you have your model trained then you can, without restart, call the parse endpoint with a payload having this format:

```
{
        q: textToParse,
        model: yourModelName
}
```

All these notes should be present on our README. At least for these new versions. We need to work on that. If you want to collaborate you're more than welcome.

**Comment by bigman73** [comment] 2017-06-15 20:45
Thanks for your detailed explanation.

I didn't see tag RASA_0.8.11_full, only RASA_0.8.10_full

The new docker images (8.7, 8.10) were pulled but for some odd reason, the same training data failed to generate model files with both new images.
I can see the console logs showing the training on going for intents and expressions, but not models are created and the /status API doesn't show the model as available.

Perhaps the payload structure has changed again?

**Comment by wrathagom** [comment] 2017-06-15 22:03
@bigman73 sorry or the poor documentation on our part. We didn't anticipate getting much traffic here since we're no the official RASA repo.

That being said we're happy to have you and are certainly happy to help work through these issues.

When I run

```
docker run -p5000:5000 -v/Users/calebkeller/Desktop/rasa-test/models:/usr/src/rasa_nlu/models --name rasa-api-test samtecspg/rasa-api:RASA_0.8.10_full start
```

and wait for things to start up before training some data

```
curl --request POST \
  --url 'http://localhost:5000/train?name=Test1234' \
  --header 'content-type: application/json' \
  --data '{\n	"rasa_nlu_data": {\n		"common_examples": [\n			{\n				"text": "hey",\n				"intent": "greet",\n				"entities": []\n			},\n			{\n				"text": "howdy",\n				"intent": "greet",\n				"entities": []\n			},\n			{\n				"text": "hey there",\n				"intent": "greet",\n				"entities": []\n			},\n			{\n				"text": "hello",\n				"intent": "greet",\n				"entities": []\n			},\n			{\n				"text": "hi",\n				"intent": "greet",\n				"entities": []\n			},\n			{\n				"text": "good morning",\n				"intent": "greet",\n				"entities": []\n			},\n			{\n				"text": "good evening",\n				"intent": "greet",\n				"entities": []\n			},\n			{\n				"text": "dear sir",\n				"intent": "greet",\n				"entities": []\n			},\n			{\n				"text": "yes",\n				"intent": "affirm",\n				"entities": []\n			},\n			{\n				"text": "yep",\n				"intent": "affirm",\n				"entities": []\n			},\n			{\n				"text": "yeah",\n				"intent": "affirm",\n				"entities": []\n			},\n			{\n				"text": "indeed",\n				"intent": "affirm",\n				"entities": []\n			},\n			{\n				"text": "that'\''s right",\n				"intent": "affirm",\n				"entities": []\n			},\n			{\n				"text": "ok",\n				"intent": "affirm",\n				"entities": []\n			},\n			{\n				"text": "great",\n				"intent": "affirm",\n				"entities": []\n			},\n			{\n				"text": "right, thank you",\n				"intent": "affirm",\n				"entities": []\n			},\n			{\n				"text": "correct",\n				"intent": "affirm",\n				"entities": []\n			},\n			{\n				"text": "great choice",\n				"intent": "affirm",\n				"entities": []\n			},\n			{\n				"text": "sounds really good",\n				"intent": "affirm",\n				"entities": []\n			},\n			{\n				"text": "i'\''m looking for a place to eat",\n				"intent": "restaurant_search",\n				"entities": []\n			},\n			{\n				"text": "I want to grab lunch",\n				"intent": "restaurant_search",\n				"entities": []\n			},\n			{\n				"text": "I am searching for a dinner spot",\n				"intent": "restaurant_search",\n				"entities": []\n			},\n			{\n				"text": "i'\''m looking for a place in the north of town",\n				"intent": "restaurant_search",\n				"entities": [\n					{\n						"start": 31,\n						"end": 36,\n						"value": "north",\n						"entity": "location"\n					}\n				]\n			},\n			{\n				"text": "show me chinese restaurants",\n				"intent": "restaurant_search",\n				"entities": [\n					{\n						"start": 8,\n						"end": 15,\n						"value": "chinese",\n						"entity": "cuisine"\n					}\n				]\n			},\n			{\n				"text": "show me chines restaurants",\n				"intent": "restaurant_search",\n				"entities": [\n					{\n						"start": 8,\n						"end": 14,\n						"value": "chinese",\n						"entity": "cuisine"\n					}\n				]\n			},\n			{\n				"text": "show me a mexican place in the centre",\n				"intent": "restaurant_search",\n				"entities": [\n					{\n						"start": 31,\n						"end": 37,\n						"value": "centre",\n						"entity": "location"\n					},\n					{\n						"start": 10,\n						"end": 17,\n						"value": "mexican",\n						"entity": "cuisine"\n					}\n				]\n			},\n			{\n				"text": "i am looking for an indian spot called olaolaolaolaolaola",\n				"intent": "restaurant_search",\n				"entities": [\n					{\n						"start": 20,\n						"end": 26,\n						"value": "indian",\n						"entity": "cuisine"\n					}\n				]\n			},\n			{\n				"text": "search for restaurants",\n				"intent": "restaurant_search",\n				"entities": []\n			},\n			{\n				"text": "anywhere in the west",\n				"intent": "restaurant_search",\n				"entities": [\n					{\n						"start": 16,\n						"end": 20,\n						"value": "west",\n						"entity": "location"\n					}\n				]\n			},\n			{\n				"text": "I am looking for asian fusion food",\n				"intent": "restaurant_search",\n				"entities": [\n					{\n						"start": 17,\n						"end": 29,\n						"value": "asian fusion",\n						"entity": "cuisine"\n					}\n				]\n			},\n			{\n				"text": "I am looking for mexican indian fusion",\n				"intent": "restaurant_search",\n				"entities": [\n					{\n						"start": 17,\n						"end": 38,\n						"value": "mexican indian fusion",\n						"entity": "cuisine"\n					}\n				]\n			},\n			{\n				"text": "central indian restaurant",\n				"intent": "restaurant_search",\n				"entities": [\n					{\n						"start": 0,\n						"end": 7,\n						"value": "central",\n						"entity": "location"\n					},\n					{\n						"start": 8,\n						"end": 14,\n						"value": "indian",\n						"entity": "cuisine"\n					}\n				]\n			},\n			{\n				"text": "bye",\n				"intent": "goodbye",\n				"entities": []\n			},\n			{\n				"text": "goodbye",\n				"intent": "goodbye",\n				"entities": []\n			},\n			{\n				"text": "good bye",\n				"intent": "goodbye",\n				"entities": []\n			},\n			{\n				"text": "stop",\n				"intent": "goodbye",\n				"entities": []\n			},\n			{\n				"text": "end",\n				"intent": "goodbye",\n				"entities": []\n			},\n			{\n				"text": "farewell",\n				"intent": "goodbye",\n				"entities": []\n			},\n			{\n				"text": "Bye bye",\n				"intent": "goodbye",\n				"entities": []\n			},\n			{\n				"text": "have a good one",\n				"intent": "goodbye",\n				"entities": []\n			}\n		],\n		"entity_examples": [\n			{\n				"entities": [\n					{\n						"start": 0,\n						"entity": "symptom",\n						"end": 11,\n						"value": "chicken pox"\n					}\n				],\n				"text": "chicken pox"\n			},\n			{\n				"entities": [\n					{\n						"start": 16,\n						"entity": "symptom",\n						"end": 27,\n						"value": "chicken pox"\n					}\n				],\n				"text": "i guess she has chicken pox"\n			},\n			{\n				"entities": [\n					{\n						"start": 13,\n						"entity": "symptom",\n						"end": 24,\n						"value": "chicken pox"\n					}\n				],\n				"text": "i think it'\''s chicken pox"\n			},\n			{\n				"entities": [\n					{\n						"start": 16,\n						"entity": "symptom",\n						"end": 27,\n						"value": "chicken pox"\n					}\n				],\n				"text": "my daughter has chicken pox"\n			},\n			{\n				"entities": [\n					{\n						"end": 20,\n						"value": "chicken pox",\n						"entity": "symptom",\n						"start": 11\n					}\n				],\n				"text": "my son has small pox"\n			},\n			{\n				"entities": [\n					{\n						"end": 17,\n						"value": "chicken pox",\n						"entity": "symptom",\n						"start": 8\n					}\n				],\n				"text": "she has small pox"\n			},\n			{\n				"entities": [\n					{\n						"end": 9,\n						"value": "chicken pox",\n						"entity": "symptom",\n						"start": 0\n					}\n				],\n				"text": "small pox"\n			}\n		]\n	}\n}'
```

I can confirm that the `/status` endpoint works and persists the model.

```
curl --request GET \
  --url http://localhost:5000/status
```

returns

```
{
	"available_models": [
		"/usr/src/rasa_nlu/models/Test1234"
	],
	"trainings_under_this_process": 0
}
```

To better help you can you provide me with the docker command you're using to run things as well as your training data. Also are you running on unix or on windows?

**Comment by bigman73** [comment] 2017-06-16 13:19
Again I thank you! Unfortunately it still doesn't work.

I followed the suggestions,  almost step by step (your local path has no c drive - but the same path structure works for the docker tag of Rasa latest - 0.7.3). 
I'm running docker on Windows 7 64.
`docker run -p5810:5000 -v/c/Users/MYUSER/Documents/Kitematic/rasa-api/models:/usr/src/rasa_nlu/models --name rasa-api-810 samtecspg/rasa-api:RASA_0.8.10_full start`

The training took a lot of time for the same data model used above but in the end no model was trained 
`{
    "available_models": [],
    "trainings_under_this_process": 0
}`

The docker log:
```
"INFO:root:Started http server on port 5000
192.168.99.1 - - [2017-06-16 12:39:02] "GET / HTTP/1.1" 200 120 0.002332
192.168.99.1 - - [2017-06-16 12:39:12] "GET / HTTP/1.1" 200 120 0.000479
192.168.99.1 - - [2017-06-16 12:39:14] "GET / HTTP/1.1" 200 120 0.000663
192.168.99.1 - - [2017-06-16 12:39:14] "GET /favicon.ico HTTP/1.1" 404 342 0.005679
INFO:root:Starting model training
INFO:root:Training process <Process(Process-1, started)> started
192.168.99.1 - - [2017-06-16 12:41:52] "POST /train?name=Test1234 HTTP/1.1" 200 188 0.026333
INFO:root:Added 'nlp_mitie' to component cache. Key 'nlp_mitie-/usr/src/rasa_nlu/data/total_word_feature_extractor.dat'.
INFO:root:Training data format at /tmp/tmpzCJt_b_training_data.json is rasa_nlu
INFO:root:Training data stats: 
- intent examples: 40 (4 distinct intents)
- found intents: affirm, goodbye, greet, restaurant_search
- entity examples: 16 (3 distinct entities)
- found entities: cuisine, location, symptom
2017-06-16T12:41:56.503951891Z 
INFO:root:Starting to train component nlp_mitie
INFO:root:Finished training component.
INFO:root:Starting to train component tokenizer_mitie
INFO:root:Finished training component.
INFO:root:Starting to train component ner_mitie
Training to recognize 3 labels: 'symptom', 'location', 'cuisine'
Part I: train segmenter
words in dictionary: 200000
num features: 271
now do training
C:           20
epsilon:     0.01
num threads: 1
cache size:  5
max iterations: 2000
loss per missed segment:  3
C: 20   loss: 3 	0.722222
C: 35   loss: 3 	0.722222
C: 20   loss: 4.5 	0.722222
C: 5   loss: 3 	0.722222
C: 20   loss: 1.5 	0.888889
C: 20   loss: 1 	0.777778
C: 21.5   loss: 1.35 	0.888889
C: 23.4601   loss: 1.64458 	0.888889
C: 18.6742   loss: 1.63258 	0.888889
C: 20.6232   loss: 1.67684 	0.888889
C: 20.6548   loss: 1.57558 	0.888889
best C: 20
best loss: 1.5
num feats in chunker model: 4095
train: precision, recall, f1-score: 1 1 1 
Part I: elapsed time: 2 seconds.
2017-06-16T12:42:02.727515685Z 
Part II: train segment classifier
now do training
num training samples: 18
C: 200   f-score: 0.9375
C: 400   f-score: 0.9375
C: 300   f-score: 0.9375
192.168.99.1 - - [2017-06-16 12:42:12] "GET /status HTTP/1.1" 200 175 0.026073
C: 100   f-score: 0.9375
C: 0.01   f-score: 0.9375
192.168.99.1 - - [2017-06-16 12:42:17] "GET /status HTTP/1.1" 200 175 0.023847
C: 50.005   f-score: 0.9375
192.168.99.1 - - [2017-06-16 12:42:18] "GET /status HTTP/1.1" 200 175 0.003464
192.168.99.1 - - [2017-06-16 12:42:20] "GET /status HTTP/1.1" 200 175 0.004703
C: 25.0075   f-score: 0.9375
192.168.99.1 - - [2017-06-16 12:42:21] "GET /status HTTP/1.1" 200 175 0.002719
C: 12.5088   f-score: 0.9375
C: 6.25938   f-score: 0.9375
C: 3.13469   f-score: 0.9375
C: 1.57234   f-score: 0.9375
C: 0.791172   f-score: 0.9375
C: 0.400586   f-score: 0.9375
best C: 0.791172
test on train: 
7 0 0 
0 4 0 
0 0 7 
2017-06-16T12:42:40.952586777Z 
overall accuracy: 1
Part II: elapsed time: 38 seconds.
df.number_of_classes(): 3
INFO:root:Finished training component.
INFO:root:Starting to train component ner_synonyms
INFO:root:Finished training component.
INFO:root:Starting to train component intent_classifier_mitie
Training to recognize 4 categories: 'greet', 'affirm', 'restaurant_search', 'goodbye'
Train classifier
extracting text features
now do training
num training samples: 40
192.168.99.1 - - [2017-06-16 12:42:58] "GET /status HTTP/1.1" 200 175 0.031131
C: 200   f-score: 0.657895
192.168.99.1 - - [2017-06-16 12:43:22] "GET / HTTP/1.1" 200 120 0.011426
C: 400   f-score: 0.657895
C: 300   f-score: 0.657895
192.168.99.1 - - [2017-06-16 12:44:12] "GET / HTTP/1.1" 200 120 0.034383
C: 100   f-score: 0.657895
C: 0.01   f-score: 0.631579
C: 600   f-score: 0.657895
C: 1400   f-score: 0.657895
C: 3000   f-score: 0.657895
C: 5000   f-score: 0.657895
C: 2550   f-score: 0.657895
C: 1325   f-score: 0.657895
C: 712.5   f-score: 0.657895
C: 406.25   f-score: 0.657895
C: 253.125   f-score: 0.657895
C: 176.562   f-score: 0.657895
C: 138.281   f-score: 0.657895
C: 119.141   f-score: 0.657895
C: 109.57   f-score: 0.657895
C: 104.785   f-score: 0.657895
192.168.99.1 - - [2017-06-16 12:50:27] "GET / HTTP/1.1" 200 120 0.019004
C: 102.393   f-score: 0.657895
C: 101.196   f-score: 0.657895
C: 100.598   f-score: 0.657895
C: 100.299   f-score: 0.657895
best C: 100.598
192.168.99.1 - - [2017-06-16 12:54:17] "GET / HTTP/1.1" 200 120 0.020367
192.168.99.1 - - [2017-06-16 12:55:31] "GET /status HTTP/1.1" 200 175 0.018467"
```

**Comment by bigman73** [comment] 2017-06-16 13:25
Some more clarification - this might have to do with the pay load and other factors (memory? rasa bug?)
I ran the simple payload (below) on 0.7.3, 0.8.7, 0.8.10 - the all produce trained models
for 0.8.10 the status returns as expected:
`{
    "available_models": [
        "/usr/src/rasa_nlu/models/Test1234"
    ],
    "trainings_under_this_process": 0
}`

simple payload:
`{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "show me chinese restaurants",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 8,
            "end": 15,
            "value": "chinese",
            "entity": "cuisine"
          }
        ]
      },
	  {
        "text": "do you know chinese restaurants?",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 12,
            "end": 19,
            "value": "chinese",
            "entity": "cuisine"
          }
        ]
      }
    ]
  }
}`

**Comment by dcalvom** [comment] 2017-06-16 16:59
Hi @bigman73,

I also use Docker on Windows. The only difference I use Win 10 with the "native" version of docker for Windows. I had experienced some issues when trained models with RASA and the `mitie` pipeline.

Recently we did a massive update on all branches to change the default pipeline to `spacy_sklearn`, as it is the one we use by default. If you didn't change this pipeline before you're going to notice a significant change in the time of training.

Please wait until the new images get built and try with the latest tag, as it is now up to date.

To check the status of the images building process go [here](https://hub.docker.com/r/samtecspg/rasa-api/builds/)

**Comment by dcalvom** [comment] 2017-06-16 20:06
Closing Issue according to @bigman73 [comment](https://github.com/samtecspg/rasa-api/issues/2#issuecomment-309120839) problem is solved.

**Closed by dcalvom** 2017-06-16 20:06 UTC
Labels: help wanted
